import os
import secrets

from dotenv import load_dotenv

load_dotenv()


def _env(name: str):
    """os.getenv, stripped of stray whitespace — dashboard env-var UIs
    (Railway included) have repeatedly let leading/trailing spaces sneak
    into pasted values, which silently breaks URLs and auth headers built
    from them."""
    v = os.getenv(name)
    return v.strip() if v is not None else None


DATABASE_URL = _env("DATABASE_URL") or "sqlite:///./netra.db"

# Live-scan (Microsoft Graph) credentials — from an app registered in the
# Microsoft 365 Developer Program sandbox tenant. Optional: if unset, live
# scan is simply unavailable and the app continues to work on sample data.
MS_TENANT_ID = _env("MS_TENANT_ID")
MS_CLIENT_ID = _env("MS_CLIENT_ID")
MS_CLIENT_SECRET = _env("MS_CLIENT_SECRET")

# Live-scan (GitHub) credentials — primary live-scan provider, since it needs
# no eligibility gate (unlike the Microsoft 365 Developer Program sandbox).
# GITHUB_TOKEN: a classic Personal Access Token with the "admin:org" scope,
# generated by an owner of GITHUB_ORG.
GITHUB_TOKEN = _env("GITHUB_TOKEN")
GITHUB_ORG = _env("GITHUB_ORG")

# Background scheduler — periodic re-scan + re-assess. Set to "0" to disable.
SCAN_INTERVAL_SECONDS = int(_env("SCAN_INTERVAL_SECONDS") or "1800")

# Slack Incoming Webhook — posts a real alert when a live scan finds a new
# High-risk tool. Optional: if unset, notification is simply skipped.
SLACK_WEBHOOK_URL = _env("SLACK_WEBHOOK_URL")

# Microsoft Foundry deployment of Claude Haiku 4.5 — used by risk_engine.py
# and triage_agent.py for REAL mode when set (falls back to MOCK otherwise).
ANTHROPIC_FOUNDRY_API_KEY = _env("ANTHROPIC_FOUNDRY_API_KEY")
ANTHROPIC_FOUNDRY_RESOURCE = _env("ANTHROPIC_FOUNDRY_RESOURCE")

# Shared secret the endpoint discovery agent (netra-mvp/agent/netra_agent.py)
# must present to POST /discovery/endpoint-report. Optional: if unset, the
# endpoint is simply disabled (returns 503) rather than accepting unauthenticated
# device reports.
ENDPOINT_AGENT_TOKEN = _env("ENDPOINT_AGENT_TOKEN")

# Tier-2 discovery providers — code shaped and ready, but credentials for
# both belong to systems outside this team's control. Left unconfigured
# (is_configured() returns False for both) until real access exists; see
# app/manageengine_discovery.py / app/google_workspace_discovery.py.
MANAGEENGINE_BASE_URL = _env("MANAGEENGINE_BASE_URL")
MANAGEENGINE_API_KEY = _env("MANAGEENGINE_API_KEY")

GOOGLE_WORKSPACE_CUSTOMER_ID = _env("GOOGLE_WORKSPACE_CUSTOMER_ID")
GOOGLE_WORKSPACE_SERVICE_ACCOUNT_JSON = _env("GOOGLE_WORKSPACE_SERVICE_ACCOUNT_JSON")
GOOGLE_WORKSPACE_ADMIN_EMAIL = _env("GOOGLE_WORKSPACE_ADMIN_EMAIL")

# Microsoft Sentinel push connector (app/siem/sentinel_connector.py) — posts
# real findings into a real Log Analytics workspace via the Azure Monitor
# Logs Ingestion API. Provisioned via netra-mvp/scratch_sentinel_setup.sh
# (Azure CLI), same subscription as the Foundry deployment. Optional: if
# unset, push is silently skipped, same pattern as slack_notify.py.
SENTINEL_DCE_ENDPOINT = _env("SENTINEL_DCE_ENDPOINT")
SENTINEL_DCR_IMMUTABLE_ID = _env("SENTINEL_DCR_IMMUTABLE_ID")
SENTINEL_STREAM_NAME = _env("SENTINEL_STREAM_NAME")
SENTINEL_TENANT_ID = _env("SENTINEL_TENANT_ID")
SENTINEL_CLIENT_ID = _env("SENTINEL_CLIENT_ID")
SENTINEL_CLIENT_SECRET = _env("SENTINEL_CLIENT_SECRET")

# Splunk HTTP Event Collector push connector (app/siem/splunk_connector.py)
# — coded against Splunk's real, documented HEC API, but genuinely
# unactivated: the team has no real Splunk instance/token to test against.
# Left unconfigured (is_configured() returns False) until real access
# exists, same status as manageengine_discovery.py / google_workspace_discovery.py.
SPLUNK_HEC_URL = _env("SPLUNK_HEC_URL")
SPLUNK_HEC_TOKEN = _env("SPLUNK_HEC_TOKEN")

# Login/RBAC (app/auth.py). JWT_SECRET_KEY should be set explicitly in
# production — an unset value falls back to a random key generated at
# process start, which works fine for local dev but invalidates every
# outstanding login on each restart/redeploy since the signature no longer
# matches. ADMIN_PASSWORD must be set for the bootstrap admin account to be
# created; if unset, no default user exists and login is simply unusable
# until one is created directly in the database.
JWT_SECRET_KEY = _env("JWT_SECRET_KEY") or secrets.token_urlsafe(32)
ADMIN_USERNAME = _env("ADMIN_USERNAME") or "admin"
ADMIN_PASSWORD = _env("ADMIN_PASSWORD")

# Real Celery task-queue integration (app/tasks.py) for parallelizing the
# per-tool risk-assessment step across a genuine separate worker process —
# see app/tasks.py's module docstring for why this uses Celery's filesystem
# broker rather than a deployed Redis/RabbitMQ service. Optional: if unset,
# the existing sequential in-process assessment loop runs exactly as before
# (scan_pipeline.py), same "build now, activate later" pattern as every
# other optional integration in this project.
CELERY_ENABLED = _env("CELERY_ENABLED") == "1"
CELERY_BROKER_PATH = _env("CELERY_BROKER_PATH") or "./celery_broker"
