import os
from dotenv import load_dotenv

load_dotenv()


def _env(name: str):
    """os.getenv, stripped of stray whitespace — dashboard env-var UIs
    (Railway included) have repeatedly let leading/trailing spaces sneak
    into pasted values, which silently breaks URLs and auth headers built
    from them."""
    v = os.getenv(name)
    return v.strip() if v is not None else None


DATABASE_URL = _env("DATABASE_URL") or "sqlite:///./netra.db"

# Live-scan (Microsoft Graph) credentials — from an app registered in the
# Microsoft 365 Developer Program sandbox tenant. Optional: if unset, live
# scan is simply unavailable and the app continues to work on sample data.
MS_TENANT_ID = _env("MS_TENANT_ID")
MS_CLIENT_ID = _env("MS_CLIENT_ID")
MS_CLIENT_SECRET = _env("MS_CLIENT_SECRET")

# Live-scan (GitHub) credentials — primary live-scan provider, since it needs
# no eligibility gate (unlike the Microsoft 365 Developer Program sandbox).
# GITHUB_TOKEN: a classic Personal Access Token with the "admin:org" scope,
# generated by an owner of GITHUB_ORG.
GITHUB_TOKEN = _env("GITHUB_TOKEN")
GITHUB_ORG = _env("GITHUB_ORG")

# Background scheduler — periodic re-scan + re-assess. Set to "0" to disable.
SCAN_INTERVAL_SECONDS = int(_env("SCAN_INTERVAL_SECONDS") or "1800")

# Slack Incoming Webhook — posts a real alert when a live scan finds a new
# High-risk tool. Optional: if unset, notification is simply skipped.
SLACK_WEBHOOK_URL = _env("SLACK_WEBHOOK_URL")

# Microsoft Foundry deployment of Claude Haiku 4.5 — used by risk_engine.py
# and triage_agent.py for REAL mode when set (falls back to MOCK otherwise).
ANTHROPIC_FOUNDRY_API_KEY = _env("ANTHROPIC_FOUNDRY_API_KEY")
ANTHROPIC_FOUNDRY_RESOURCE = _env("ANTHROPIC_FOUNDRY_RESOURCE")
