import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./netra.db")

# Live-scan (Microsoft Graph) credentials — from an app registered in the
# Microsoft 365 Developer Program sandbox tenant. Optional: if unset, live
# scan is simply unavailable and the app continues to work on sample data.
MS_TENANT_ID = os.getenv("MS_TENANT_ID")
MS_CLIENT_ID = os.getenv("MS_CLIENT_ID")
MS_CLIENT_SECRET = os.getenv("MS_CLIENT_SECRET")

# Live-scan (GitHub) credentials — primary live-scan provider, since it needs
# no eligibility gate (unlike the Microsoft 365 Developer Program sandbox).
# GITHUB_TOKEN: a classic Personal Access Token with the "admin:org" scope,
# generated by an owner of GITHUB_ORG.
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_ORG = os.getenv("GITHUB_ORG")

# Background scheduler — periodic re-scan + re-assess. Set to "0" to disable.
SCAN_INTERVAL_SECONDS = int(os.getenv("SCAN_INTERVAL_SECONDS", "1800"))

# Slack Incoming Webhook — posts a real alert when a live scan finds a new
# High-risk tool. Optional: if unset, notification is simply skipped.
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")
